name: gpu_env
channels:
  - defaults
  - conda-forge
  - bioconda
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anndata=0.11.4=pyhd8ed1ab_0
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.6.0=h6a678d5_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h5764c6d_2
  - arpack=3.7.0=hdefa2d7_2
  - array-api-compat=1.12.0=pyhe01879c_0
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.5=py310h06a4308_0
  - biothings_client=0.2.6=pyh7cba7a3_1
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h4eded50_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - ctgan=0.11.1=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py310hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - faker=37.12.0=pyhd8ed1ab_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.17.0=py310h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py310hee96239_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - glpk=4.65=h9202a9a_1004
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - gseapy=1.1.10=py310hec43fc7_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.14.0=py310he0d80d8_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipykernel=7.0.1=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.5.2=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lark=1.3.0=pyhd8ed1ab_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.14.1.1=4
  - libcups=2.4.2=h252cb56_2
  - libcurand=10.3.10.19=0
  - libcurl=8.15.0=hc1efc7f_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libopengl=1.7.0=h5eee18b_2
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.43.0=py310h6a678d5_1
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib=3.10.6=py310h06a4308_0
  - matplotlib-base=3.10.6=py310h71dd3da_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mesalib=25.1.5=h31e3550_0
  - metis=5.1.0=h58526e2_1006
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0=mpich
  - mpi4py=3.1.3=py310h37cc914_1
  - mpich=4.0.2=h846660c_100
  - mpmath=1.3.0=py310h06a4308_0
  - mygene=3.2.2=pyh5e36f6f_0
  - mysql-common=9.3.0=h0021b1a_3
  - mysql-libs=9.3.0=h797a5cd_3
  - narwhals=2.10.2=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py310h06a4308_0
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.60.0=py310h6a678d5_1
  - numexpr=2.11.0=py310hf4471f9_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=py310h06a4308_0
  - pandas=2.3.3=py310h505adc9_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310hb1c3d2d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - polars=1.34.0=py310hac84d7e_0
  - polars-runtime-32=1.34.0=py310hbdd6827_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.0.0=py310hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=py310h06a4308_0
  - pyopengl=3.1.9=pyhd8ed1ab_0
  - pyparsing=3.2.0=py310h06a4308_0
  - pyqt=6.9.1=py310hc79087c_0
  - pyqt6-sip=13.10.2=py310hee96239_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.1.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=27.1.0=py310hcf8288c_0
  - qtbase=6.9.2=h46e0f57_1
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - rdt=1.18.2=pyhd8ed1ab_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=py310h06a4308_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.22.3=py310h4aa5aa6_0
  - scanpy=1.10.4=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h505adc9_0
  - scipy=1.15.3=py310h525edd1_0
  - seaborn=0.13.2=py310h06a4308_3
  - send2trash=1.8.3=pyh0d859eb_1
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=80.9.0=py310h06a4308_0
  - sip=6.12.0=py310h7934f7d_0
  - six=1.17.0=py310h06a4308_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=py310h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.13.2=py310h96516ba_0
  - stdlib-list=0.11.1=pyhd8ed1ab_0
  - suitesparse=5.10.1=h9e50725_1
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.18.1=pyh0d859eb_0
  - texttable=1.7.0=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py310h06a4308_0
  - torchaudio=2.1.0=py310_cu118
  - torchtriton=2.1.0=py310
  - torchvision=0.16.0=py310_cu118
  - tornado=6.5.1=py310h5eee18b_0
  - tqdm=4.67.1=py310h2f386ee_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - umap-learn=0.5.4=py310h06a4308_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=py310h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - x264=1!157.20191217=h7b6447c_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - cell-gears==0.0.2
      - chex==0.1.90
      - click==8.3.1
      - datasets==2.21.0
      - dcor==0.6
      - deprecated==1.3.1
      - dill==0.3.8
      - docrep==0.3.2
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - etils==1.13.0
      - flash-attn==2.8.3
      - flax==0.10.7
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - hf-xet==1.2.0
      - huggingface-hub==1.1.4
      - humanize==4.14.0
      - igraph==1.0.0
      - importlib-resources==6.5.2
      - jax==0.6.2
      - jaxlib==0.6.2
      - leidenalg==0.11.0
      - lightning-utilities==0.15.2
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - ml-dtypes==0.5.4
      - msgpack==1.1.2
      - mudata==0.3.2
      - multidict==6.7.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.16
      - numpy==1.26.4
      - numpyro==0.19.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.6
      - orbax==0.1.7
      - orbax-checkpoint==0.11.28
      - pot==0.9.6.post1
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pydot==4.0.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytorch-lightning==1.9.5
      - rich==14.2.0
      - scgpt==0.2.4
      - scib==1.1.7
      - scikit-misc==0.5.2
      - scvi-tools==0.20.3
      - shellingham==1.5.4
      - simplejson==3.20.2
      - sympy==1.13.1
      - tensorstore==0.1.78
      - toolz==1.1.0
      - torchmetrics==1.8.2
      - torchtext==0.18.0
      - treescope==0.1.10
      - typer-slim==0.20.0
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /data/mriza/anaconda3/envs/gpu_env
